### ISSUE TITLE
change op_host config param to "op_discovery_uri"

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#158]
![image](https://user-images.githubusercontent.com/3717101/36347802-5b9247b0-1426-11e8-985b-bb818b7771b3.png)

In dynamic client registration, the configuration endpoint URL may contain an optional path. For example, `https://op.example.com/acme/.well-known/openid-configuration`.

**Comment by duttarnab** [comment]
@yuriyz , @nynymike , as per my understanding, there may be multiple `configuration endpoint URL` paths for an op_host. Through this ticket, we will define all the configuration paths in an array. So that if one path is not available then oxd can switch to another path from the array. Please confirm if this understanding is correct.

**Comment by yuriyz** [comment]
While I guess it would be more clear to have `op_discovery_uri`, we named it `op_host` not only in configuration but also in request parameters (see swagger https://github.com/GluuFederation/oxd/blob/3ede32139354d159e87aa8085491581f9fb97d77/oxd-server/src/main/resources/swagger.yaml#L328)

If we renamed configuration parameter then we should probably renamed also API parameters in all commands to keep it consistent. We can do that but in major release, e.g 5.0. Lets postpone it.

Re: path in discovery it's covered by `op_discovery_path`. So with `https://op.example.com/acme/.well-known/openid-configuration` example above it will look:

- op_uri=https://op.example.com
- op_discovery_path=/acme

@duttarnab it's about  more clear name for OP discovery URI and also join together `op_uri` and `op_discovery_path` since now it's a bit confusing.

**Comment by nynymike** [comment]
We can continue to support op_host and add this as an additional param?  I thought about using a path param, but it may just confuse.

An OP will only have one configuration endpoint for openid.

**Comment by yuriyz** [comment]
We can add additional parameter. Question is what should we do with swagger spec. We can't remove old because during client re-generation it will break app code that is using it. If we add that additional parameter we will have at the same time 3 parameters for discovery in swagger spec: `op_host`, `op_discovery_path` and `op_discovery_uri`. It will confuse more.

**Comment by yuriyz** [comment]
@nynymike @duttarnab OK, lets add `op_discovery_uri`. Swagger supported `deprecated: true`, so we can mark `op_host` and `op_discovery_path` as deprecated but still use it. Re-scheduling to 4.2.

**Comment by nynymike** [comment]
Better would be `op_configuration_endpoint`

**Comment by yuriyz** [comment]
Agreed.

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/oxd/pull/421 and https://github.com/GluuFederation/docs-oxd-prod/pull/84
