### ISSUE TITLE
grant_type parrameter is not working

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxd#17]
When I change grant_type in oxd-default-site-config.json and then usenig register_site protocol, in gluu server Response Type is not changed, alweys accept  Authorization Code Grant Type ,Implicit , Grant Type, ID Toke.
@yuriyz , If You remember I talked to You about it.

**Comment by yuriyz** [comment]
fixed in 3.0.7-SNAPSHOT version http://ox.gluu.org/maven/org/xdi/oxd-server/3.0.7-SNAPSHOT/

Grant types are loaded:
1. From RegisterSite command parameters
2. if absent in parameters then load from oxd-default-site-config.json
3. if absent also in oxd-default-site-config.json then put all possible grant types.

Please let me know whether it works for you as expected.
