### ISSUE TITLE
problem with scopes in get_tokens_by_code protocol

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxd#18]
when I am sending new scopes in scopes (without openid and profile) for example address, email, mobile_phone, phone or new custom scopes, response is empty without openid and profile response parameters, but when i am adding new parameters in scope profile (for example email, phone and etc.) response already ok, but I need to be it work multiple, what i send with arc_value if in gluu server it is exist and switched on it sent me response, what I want

**Comment by nynymike** [comment]
I can't understand the content of this issue. Please check the english grammer before you submit. Use shorter sentences--this issue is one long, unintelligible, run-on sentence. 

Here are a few thoughts:

1. openid is a required scope. If openid scope is not present, you are not using OpenID Connect. Bad things will certainly happen.
2. acr is used to specify the type of authentication requrested, and has nothing to do with scopes. The acr value corresponds to the name of the custom authentiation script.

**Comment by dollar007** [comment]
I mean when I send acr_value with parameter ['openid', 'profile'] then oxd-server responses me all climes, which contain these scopes, but when I send acr_value with parameter ['openid', 'profile', 'email', 'phone', 'address']  then responses me only openid, profile belonging climes's, I can not get user info about email addresses, phone and etc. climes's.

**Comment by yuriyz** [comment]
This has to work with http://ox.gluu.org/maven/org/xdi/oxd-server/3.0.7-SNAPSHOT/

If it still does not work for you, please attach oxd-server.log to this issue and reopen it, so I can check it step by step.
