### ISSUE TITLE
Bug(?): internal server error

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#194]
Preconditions: GG installed on the same virtual machine together with oxd, both running
Tested on Ubuntu 16.04 and 14.04

Steps:
1. Log in to the GG Admin Portal
2. Switch off the virtual machine
3. Wait several hours
4. Switch it back on
5. Try to log in to the Admin Portal again

Expected: The user is able to log in OR the user is unable to log in, but there's a meaningful error text displayed
Actual: There's only info about an internal server error (see the screenshot).
![2018-06-04_20h23_37](https://user-images.githubusercontent.com/38302725/40913353-b46d42da-6837-11e8-903d-1d05b8a88abd.png)
[oxd-server(1).log](https://github.com/GluuFederation/oxd/files/2067909/oxd-server.1.log)

When I leave the machine running for several hours and the GG session expires, it's possible to get also this error. It might be connected with a slow Internet connection, but for better UX I recommend something more user-friendly.
[oxd-server.log](https://github.com/GluuFederation/oxd/files/2071272/oxd-server.log)

![2018-06-05_16h13_43](https://user-images.githubusercontent.com/38302725/40958219-d82f4e58-68db-11e8-8e5c-675ad6c9f075.png)

**Comment by yuriyz** [comment]
It seems that VM on which you run oxd-server lost internet connection and as result oxd-server was not able to operate in normal mode. Logs are full of errors like:
```
2018-06-04 11:17:24,195 ERROR [org.xdi.oxd.server.service.DiscoveryService] Unable to fetch discovery information for op_host: https://ce-dev6.gluu.org
```
And
```
Caused by: java.net.UnknownHostException: license.gluu.org
```
About error message, please open ticket to improve it on GG. Hopefully GG can identify when internet goes down. oxd-server returns internal error because if it gets exception like `java.net.UnknownHostException` or `NullPointerException` from technical point of view it can not report that internet is down because it may be mis-configuration.
