### ISSUE TITLE
Revise /register-site and /setup-client and check whether we can stick with one single command for registration.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#220]
Revise /register-site and /setup-client and check whether we can stick with one single command for registration.

**Comment by ldeveloperl1985** [comment]
I think, we need to stick with one single command(name: /setup-client) that means only single client use as regular client and same client for permission_access_token, because we are creating client in plugins configuration. If we create two clients(1. setup-client with setup-client command 2.regular client using register-site command) then we need to manage both clients in plugin.

Below sequence diagram of OAuth2 plugin configuration, when we go with two clients. [sequence-text](https://www.websequencediagrams.com/?lz=dGl0bGUgT0F1dGggcGx1Z2luIGNvbmZpZ3VyYXRpb24KCmxvb3AgQ3JlYXRlIFNlcnZpY2UmUm91dGUKa29uZ2EtPmtvbmc6ABoIcwAcBiB3aXRoIHVybDogImh0dHBzOi8vZGVtby5jb20iADQFADIGYTogUmVzcG9ucwAsBwA4CG9iamVjdABOFXJvdXQAIA5faWQAOBxyAFoIAE4HZW5kCgphbHQgTmV3IENsaWVudAogICAgAIFJB294ZACBRAt0dXAgYwAfBSgACAUtAAcGKQAtBW94ZC0-T1A6ADoFT1AANgYAEAoAgVkJdHVybgCBWAgARwoAXRhyZWd1bGFyAG8IcmVnaXN0ZXJfc2l0ZQBAOABGDgCBYwwAg0EFX0RCOiBTdG9yZQCBZgdfY3JlZGVudGlhbHMAghgFbm90ZSBvdmVyAIIhBl9EQgCCLwUAgX8HX2lkIC0gdXNlZCBmb3IgaW50cm9zcGVjdGlvbiwAIAkAVAcAIgp0byBzaG93IG94ZCBlLWNvbW0gcmVwb3J0ACMRc2VjcmV0AA0rAIM1BV8AgQ0OAA4pAIEVFGdldCBwcm90AIFPBiB0b2tlAIFQCwArDQCBHBEAKBQAhG4FZW5kAIJVBQplbHNlIFVzZSBFeGlzdGluZwCFDQwAgm0PAIJwCVVzZXIgY2FuIHVzZSBlADEIAIUoBiAAgzEQAGkGdGVyAIMGKgApBgCDAjQALQ0AgwsxAIEhBgCDCzcAMQwAgxYyACsTAIMbMwCGMS4AiQsFAIo_DgCKfAdlIEdsdXUtAIsaBTItAIklBgCLHwgAil0FWwCLCwd8AIsNBXxBUEl8R2xvYmFsXQoAhyMOCgA2E3NjaGVtYToKMS4AhzwHCjIuAIVxEAozAAQPAIcDBgo0LiBvcF9zZXJ2ZXIKNQA7Bmh0dHBfdXJsCjYuIG1vZGUgeyJPQVVUSCIsIlVNQSIsIk1JWCJ9CjcuIGFub255bW91cwo4LiBvYXV0aF9zY29wZV9leHByZXNzaW9uCjkuIGFsbG93XwAJFwCGMgkAjEQKAIlBBUFkZACCKgwAjSEFX0RCAI0hBwCMbBAAixAKZ2x1dS0AgQcFMgCNfAcgZGV0YWlscwo&s=default)
![oauth_plugin_config](https://user-images.githubusercontent.com/2329776/44207153-baafd380-a179-11e8-88f2-b28e75de3524.png)

**Comment by ldeveloperl1985** [comment]
Sequence diagram with single client. Same client used as regular client and for permission_access_token. 
[sequence test](https://www.websequencediagrams.com/?lz=dGl0bGUgT0F1dGggcGx1Z2luIGNvbmZpZ3VyYXRpb24KCmxvb3AgQ3JlYXRlIFNlcnZpY2UmUm91dGUKa29uZ2EtPmtvbmc6ABoIcwAcBiB3aXRoIHVybDogImh0dHBzOi8vZGVtby5jb20iADQFADIGYTogUmVzcG9ucwAsBwA4CG9iamVjdABOFXJvdXQAIA5faWQAOBxyAFoIAE4HZW5kCgphbHQgTmV3IENsaWVudAogICAgAIFJB294ZACBRAt0dXAgYwAfBSgACAUtAAcGKQAtBW94ZC0-T1A6ADoFT1AANgYAEAoAgVkJdHVybgCBWAgARwoAaQwAgkcFX0RCOiBTdG9yZQBsB19jcmVkZW50aWFscwCBHgVub3RlIG92ZXIAgScGX0RCAIE1BQCBBQdfaWQgLSB1c2VkIGZvciBpbnRyb3NwZWN0aW9uLAAgCQBUBwAiCnRvIGdldCBwZXJtaXNzaW9uLXRva2UAIBJzZWNyZXQAFx8AgkUFZW5kAIEmBQplbHNlIFVzZSBFeGlzdGluZwCCZAwAgT4PAIFBCVVzZXIgY2FuIHVzZSBlADEIAIJ_BiAAggIQAGkGdGVyAIFXKgApBgCBVTIAKw0AgVozAINBLgCFIQUAhlUOAIcSB2UgR2x1dS0AhzAFMi0AhTsGAIc1CACGcwVbAIchB3wAhyMFfEFQSXxHbG9iYWxdCgCEMw4KADYTc2NoZW1hOgoxLgCETAcKMi4AhCoKCjMABAkAhAkGCjQuIG9wX3NlcnZlcgo1AC8GaHR0cF91cmwKNi4gbW9kZSB7Ik9BVVRIIiwiVU1BIiwiTUlYIn0KNy4gYW5vbnltb3VzCjguIG9hdXRoX3Njb3BlX2V4cHJlAIUJBQo5LiBhbGxvd18ACRcAhGUJAIhOCgCGRQVBZGQAgh4MAIkrBV9EQgCJKwcAiHYQAIcaCmdsdXUtAIEHBTIAigYHIGRldGFpbHMK&s=default)

![oauth_plugin_config_with_one_client](https://user-images.githubusercontent.com/2329776/44209924-84c31d00-a182-11e8-8868-1fe4b9409598.png)

**Comment by yuriyz** [comment]
We are going to remove `setup_client` command completely. We will have `register_site` only.

Advantage of `setup_client` was that it sets/adds required data for protection_access_token flow which is:
- grant_type `client_credentials`
- scope `uma_protection` (required for introspection in 3.1.3 but optional since 3.1.4)
- scope `oxd` (required since 3.1.4)

However since later we added `oxd_id` to it and unlocked for regular use, it does not make much sense to maintain both `register_site` and `setup_client` commands.

Idea is to remove `setup_client` command and add `client_id` and `client_secret` to `register_site`. It is responsibility of client application to provide valid data for protection_access_token (as described above).
We remove `setup_client` because `register_site` sounds better in context of `update_site` and `remove_site` commands.

**Comment by yuriyz** [comment]
done in 4.0.0
