### ISSUE TITLE
Internal Server Error (500) while making get-tokens-by-code call

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#279]
**Ubuntu 14 + oxd-server 4.0beta**

Steps:

1. Make the following calls: `register-site, get-client-token, get-authorization-url`
2. Copy the state from the authorization-url
3. Log in to the OP
4. Open the authorization-url in the browser and copy the code from the redirection uri
5. Make a `get-tokens-by-code` call with the copied data and the oxd_id from the `register-site` call

Expected: The call is successful (200)
Actual: There is an internal server error (500)

**Last two errors in the log:**
[28_11_oxd-server.log.tar.gz](https://github.com/GluuFederation/oxd/files/2623707/28_11_oxd-server.log.tar.gz)

**Comment by shoebkhan09** [comment]
To get the actual code, rather than using redirect uri's code query parameter (as mentioned in step 4),  call to /get-authorization-code endpoint is required. Server's potentially misleading response, as mentioned in this issue, is going to be taken care of by resolution of issue@283.

**Comment by duttarnab** [comment]
I followed the steps using the parameters from the attached log file (only changed 'op_host', 'authorization_redirect_uri', 'redirect_uris'). It worked perfectly and /get-tokens-by-code returned the token. 
According to the logs files attached, the error is "org.h2.jdbc.JdbcSQLException: No data is available". It appears it is not able to find token in h2 database.

As this issue was raised 5 months before, it appears this has been already address. Can you please check it again and revert with the log file in case same issue is found again.

**Comment by yuriyz** [comment]
not reproducible, @MohitMaliFtechiz  please validate.
