### ISSUE TITLE
add `idTokenSignedResponseAlg` to `/register-site` command

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#338]
add `idTokenSignedResponseAlg` to `/register-site` command

**Comment by duttarnab** [comment]
Adding below params to `/register-site` command

logoUri
clientUri
policyUri
frontChannelLogoutSessionRequired
tosUri
jwks
idTokenBindingCnf
tlsClientAuthSubjectDn
runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims
subjectType
idTokenEncryptedResponseAlg
idTokenEncryptedResponseEnc
userInfoSignedResponseAlg
userInfoEncryptedResponseAlg
userInfoEncryptedResponseEnc
requestObjectSigningAlg
requestObjectEncryptionAlg
requestObjectEncryptionEnc
defaultMaxAge
requireAuthTime
initiateLoginUri
authorizedOrigins
accessTokenLifetime
softwareId
softwareVersion
softwareStatement
customAttributes
jsonObject
authenticationMethod
authorizationMethod
customParameters

**Comment by yuriyz** [comment]
Sounds good. At the same time, lets not save it into entry, just pass to `RegisterRequest`. We don't want to double oxd database size.

**Comment by yuriyz** [comment]
done by https://github.com/GluuFederation/oxd/pull/339

**Comment by duttarnab** [comment]
Due to some confusion earlier I did not include some fields in swaggers specs and codegen-generated client. Now all fields have been included.

client_token_endpoint_auth_signing_alg
idTokenEncryptedResponseAlg
idTokenEncryptedResponseEnc
userInfoSignedResponseAlg
userInfoEncryptedResponseAlg
userInfoEncryptedResponseEnc
requestObjectSigningAlg
requestObjectEncryptionAlg
requestObjectEncryptionEnc

**Comment by duttarnab** [comment]
done by #341
