### ISSUE TITLE
Add support for proxy configuration

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxd#364]
GG requesting oxd and oxd requesting to OP which may be outside of the network so we need to add `http_proxy` configuration support in oxd.

GG issue https://github.com/GluuFederation/gluu-gateway/issues/352

**Comment by duttarnab** [comment]
@yuriyz , @ldeveloperl1985, I think https://github.com/GluuFederation/gluu-gateway/issues/352 ticket is already resolved and the solution is to export or set HTTP_PROXY and HTTPS_PROXY env. https://github.com/GluuFederation/gluu-gateway/issues/352#issuecomment-523801400


Please advise if we can close this ticket.

**Comment by yuriyz** [comment]
@duttarnab since we dive into httpclient we should : 
1) drop deprecated http client code usage (see `HttpService`), we should use `HttpClientBuilder`.
2) provide ability to set proxy via `org.apache.http.impl.client.HttpClientBuilder#setProxy`
3) add to `oxd-server.yml`, `proxy: <proxy value>` (e.g. `proxy: https://myproxy:88` or `proxy: myproxy:88`), see `org.apache.http.HttpHost#create`
4) add description of new configuration property to docs

**Comment by duttarnab** [comment]
Done in 4.2
