### ISSUE TITLE
Persist field only if it's not null into oxd db to avoid saving redundant data

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#371]
For oxd persistence layer we have to avoid persistence of field if it's `null`. Right now we save many `Rp` fields which are null. 
Use global mapper config for `Rp` particular case
```
createRpMapper() {
    ...
    mapper.setSerializationInclusion(Include.NON_NULL);
    return mapper;
}
```

Add test to make sure we do not persist redundant data. Also if needed move primitives to objects and add nullity safe code to avoid NPE.

**Comment by duttarnab** [comment]
`"Add test to make sure we do not persist redundant data"`

@yuriyz , by `redundant data` do we mean we need to check if json saved in oxd database do not have any null or empty Fields. If this understanding is correct, then I think  we need to add another `getRp(String oxdId)` method in `PersistenceServiceImpl.java` which will return json string which we will parse into Map and check if null/empty field was saved.  

This is because we cannot check this in `getRp(String oxdId)` method returning Rp object. Please confirm.

**Comment by yuriyz** [comment]
@duttarnab no need to disturb persistence service. Test should check serialization of `Rp` object.

E.g. I have Rp {oxdId="testId", idTokenSigningAlg=null}.
When you serialize object it should produce json `{"oxdId": "testId"}` (no idTokenSigningAlg because it's null and it doesn't make sense to keep null value if our default is null anyway).

Positive test
```
public void testNullFieldsAreSkipped() {
    Rp rp = createTestRp();
    assertEquals(expectedJson, Jackson.serializeWithoutNulls(rp));
}
```

Negative test
```
public void testNonNullFieldsAreAlwaysPresent() {
    Rp rp = createTestRp();
    assertEquals(expectedJson, Jackson.serializeWithoutNulls(rp)); <- here make sure expectedJson contains all non null values, to make sure serialization is correct.
}
```

**Comment by yuriyz** [comment]
done in 4.0
