### ISSUE TITLE
For client registered with "response_types=id_token" and "grant_types=implicit" , `response_type should be "token,id_token" in oxd database.

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#377]
Steps:
-------
1. Register new client in using oxd /register-site command with  "response_types=id_token" and "grant_types=implicit".

```
curl -X POST -k -H 'Content-Type: application/json' -i https://localhost:8443/register-site --data '{
  "redirect_uris": [
    "https://localhost:5053/authorization",
    "https://localhost:5053/authorization/page1",
    "https://localhost:5053/authorization/page2"
  ],
  "op_host": "https://ce-dev6.gluu.org",
  "client_name": "register_site_2",
"response_types": [
    "id_token"
  ],
  "grant_types": [
    "implicit"
  ]
  }'
```

2. The registered client on CE has "grant_types=implicit" and "response_types=token, id_token". It’s because response_type and grant_type has relation and basically depends on each other. oxauth has following logic: https://github.com/GluuFederation/oxAuth/blob/53422a7a1f2ed73d54a9a22b68fc13b7ce97df73/Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java#L319

![image](https://user-images.githubusercontent.com/32794267/65951346-8373b300-e45d-11e9-92cb-1e6489da1bf0.png)

3. The oxd database has "response_types=id_token" and "grant_types=implicit" for client.

In oxd database the client should have "response_types=token,id_token" to make it in sync with client details in CE.

**Comment by yuriyz** [comment]
What is the actual problem if oxd database has `id_token` but CE has `token,id_token`? (It happens because oxauth automatically adds `token` during registration for `implicit` grant_type during registration). What if user goes to admin GUI and change `response_type`? 

I'm not sure we should solve this issue. Lets postpone it. 

We can sync it by reading client information from OP but problems are:
1) when should we invoke it? we don't want redundant calls spamming OP.
2) right now oxd doesn't rely on internal `response_type` values. If customer really wants to keep it in sync, he/she can use `/update-site` to update values.

**Comment by duttarnab** [comment]
This issue has been already done using https://github.com/GluuFederation/oxd/issues/390. We have tested and now oxd is saving `token` response_type in its storage.
