### ISSUE TITLE
Correct security alert in test dependency

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#501]
Lets fix security alert raised by github. Automatic PR may broke build https://github.com/GluuFederation/oxd/pull/493

It may be better to update driver, see
https://github.com/GluuFederation/oxAuth/issues/1379

**Comment by duttarnab** [comment]
Hi @miltonbo, 

I have followed the changes done by you to correct the security alert. I have tried to use `htmlunit-driver`,  `selenium-htmlunit-driver` and other related selenium dependecies, but the test cases become unstable (throws different `class not found` exception) whenever I remove/upgrade `htmlunit` of `2.35.0` version. 

Could you please take a look and suggest how I can remove this security alert in oxd (with all test cases running successfully.)

**Comment by duttarnab** [comment]
Hi @yuriyz , @miltonbo , 

**I have the following findings:**

1. By upgrading `htmlunit` to 2.37.0 the test cases run on `https://ce-dev6.gluu.org/` but not on `https://jenkins-ldap.gluu.org/` where it gives below `java.net.UnknownHostException: client.example.com` (where `client.example.com` is the redirect uri host) error.
2. On removing `htmlunit` dependency we get all kinds of `ClassNotFound` exceptions. I have tried to find the root cause but could not figure out why the classes are not loaded even if they are present in added dependencies. I have given enough time on this.

```
Exception invoking click
ERROR [2020-06-15 08:33:57,072] com.gargoylesoftware.htmlunit.javascript.DefaultJavaScriptErrorListener: Error during JavaScript execution
! java.net.UnknownHostException: client.example.com
! at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
! at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
! at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
! at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
! at java.net.InetAddress.getAllByName(InetAddress.java:1192)
! at java.net.InetAddress.getAllByName(InetAddress.java:1126)
! at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
! at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
! at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
! at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
! at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
! at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
! at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
! at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
! at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
! at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:190)
! at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1436)
! at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1494)
! at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1494)
! at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1355)
! at com.gargoylesoftware.htmlunit.WebClient.download(WebClient.java:2242)

```

**Comment by miltonbo** [comment]
@yuriyz @duttarnab Finally I got it working, all changes were done in branch `issue/501/tmp`, probably Arnab will need to clean those commits, since I did many tests with Jenkins, anyway, basically I updated all Selenium dependencies based on `oxAuth` changes, however there are some tests with configuration a little messy I think, because It generated many issues in my local env in order to get them running.

Please check them out and let me know if that's good enough.

I executed twice Jenkins with that branch:
https://ox.gluu.org/jenkins/job/oxD_master/229
https://ox.gluu.org/jenkins/job/oxD_master/228

**Comment by yuriyz** [comment]
@miltonbo great, thanks! 
@duttarnab please open PR after clean up.

**Comment by duttarnab** [comment]
wow! the test cases ran successfully for me. Thanks @miltonbo 
@yuriyz , I have raised PR.

**Comment by duttarnab** [comment]
Done in 4.2
